version: "2.1"

services:
  postgres:
    image: "postgres:alpine"
    volumes:
      - ${PWD-.}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      PGDATA: /tmp
      # PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - ${PWD-.}/:/go/src/github.com/ld100/goblet
    working_dir: /go/src/github.com/ld100/goblet
    # command: go run cmd/goblet/main.go
    command: /bin/sh bin/start.sh
    environment:
      APP_NAME: goblet
      APP_ENV: development
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_NAME: goblet_development
      REDIS_URL: redis:6379
      SECRET_KEY: "7814aa5476dccd9efa87eaded6968b72d125ae0214b98e2b415820800109b803302d1064a514da3f01ff24841023ca6b5d8c1c9c9d02b496588d07aec6a55c8a"
      SESSION_TTL_HOURS: 24
      PROMETHEUS_ENABLED: "true"
      LOGSTASH_ENABLED: "true"
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - postgres
    depends_on:
     - postgres
     - logstash
     - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
     - ${PWD-.}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     # - ${PWD-.}/data/prometheus:/prometheus
    ports:
     - 9090:9090
    depends_on:
     - exporter

  exporter:
    image: "prom/node-exporter:latest"
    ports:
     - "9100:9100"
#    network_mode: host

  grafana:
    image: "grafana/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - ${PWD-.}/data/grafana:/var/lib/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prometheus

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0"
    volumes:
      - ${PWD-.}/config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      # - ${PWD-.}/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    image: "docker.elastic.co/logstash/logstash-oss:6.1.0"
    volumes:
      - ${PWD-.}/config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ${PWD-.}/config/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.1.0"
    volumes:
      - ${PWD-.}/config/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
