version: "2"

services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      PGDATA: /tmp
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - .:/go/src/github.com/ld100/goblet
    working_dir: /go/src/github.com/ld100/goblet
    command: go run main.go
    links:
      - postgres
    environment:
      REDIS_URL: redis:6379
      APP_ENV: development
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: ''
      DB_NAME: app_development
    ports:
      - '8080:8080'
      - '8443:8443'
  prom:
    image: quay.io/prometheus/prometheus:latest
    volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#    command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000"
    ports:
     - 9090:9090
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
#    network_mode: host
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prom