version: "2"

services:
  app:
    build: .
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
    ports:
      - '8080:8080'
      - '8443:8443'

  redis:
    image: redis:alpine