version: "2.1"

services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - ${PWD-.}/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      PGDATA: /tmp
      # PGDATA: '/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - ${PWD-.}/:/go/src/github.com/ld100/goblet
    working_dir: /go/src/github.com/ld100/goblet
    command: go run cmd/gobletsrv/main.go
    environment:
      REDIS_URL: redis:6379
      APP_ENV: development
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ''
      DB_NAME: goblet_development
      SECRET_KEY: '7814aa5476dccd9efa87eaded6968b72d125ae0214b98e2b415820800109b803302d1064a514da3f01ff24841023ca6b5d8c1c9c9d02b496588d07aec6a55c8a'
      SESSION_TTL_HOURS: 24
    ports:
      - '8080:8080'
      - '8443:8443'
    links:
      - postgres
    depends_on:
     - postgres

  prometheus:
    image: prom/prometheus
    volumes:
     - ${PWD-.}/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
    depends_on:
     - exporter

  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
#    network_mode: host

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - ${PWD-.}/grafana-data:/var/lib/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prometheus