# Redis Pure Go Library
[[constraint]]
  name = "gopkg.in/redis.v4"
  version = "4.2.4"

# Chi HTTP Router/Framework
[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.1"

# Chi Json Web Token middleware
[[constraint]]
  name = "github.com/go-chi/jwtauth"
  version = "3.1.3"

# Golang implementation of JSON Web Tokens (JWT)
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

# Logrus logging library
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

# Logrus middleware for CHI
[[constraint]]
    name = "github.com/pressly/lg"
    version = "1.0.0"

# Postgres pure Go library
[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

#[[constraint]]
#  name = "github.com/jinzhu/gorm"
#  branch = "master"

# ORM
[[constraint]]
  name = "gopkg.in/jinzhu/gorm.v2"
  version = "v2"

# Manual migrations for ORM
[[constraint]]
  name = "gopkg.in/gormigrate.v1"
  version = "1.2.0"

# Validating ORM models
[[constraint]]
  name = "github.com/qor/validations"
  branch = "master"

# Prometheus montoring client
[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"