[[constraint]]
  name = "gopkg.in/redis.v4"
  version = "4.2.4"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"